### ISSUE TITLE
wfs overlays to-do list

### ISSUE THREAD

**Issue by nacholuesia9** [nacholuesia9/cosmoscout-vr#1]
- [x] At the beginning of the **Plugin : : setWFSServer**, when loading the XML file, i used mWfs[0]. I have to make it general for other servers. 
- [x] Also for different sets of data given a server. 
- [x] Set this server/dataset choice into the **GUI** ( mGuiManager->getGui()->registerCallback...).
- [x] In the WFSTypes, immplement the properties variable using a **map**. "DescribeFeatureType" (.xsd files) might be useful here
- [ ] About the rendering: Adjusting the appearance of the different elements displayed. Change the **color, size, and shape** (for now they are only squares).
- [x]  About the rendering: Making more options selectable: **lines, polygons...** 
- [x] Correct the lattiude errors in CS.
- [ ] Make an optional bbox input at the GUI
- [ ] Make shared windows for similar kind of data (e.g. rivers, country borders etc)
- [ ] Consider more bodies
- [ ] Introduce time dependency
- [ ] Edit the description given at cosmoscout

**Comment by nacholuesia9** [comment]
Make an optional bbox input at the GUI

**Comment by nacholuesia9** [comment]
Make shared windows for similar kind of data (e.g. rivers, country borders etc)
